on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.repository == 'mmjmanders/daylight-visualizer'
    steps:
      - uses: actions/checkout@v5
      - run: gh pr merge $PR_NUMBER --auto --squash --delete-branch
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
