on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  pnpm_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - run: |
          pnpm install --prefer-offline --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    needs:
      - pnpm_install
    steps:
        - run: |
            pnpm build

        - uses: actions/upload-pages-artifact@v3
          with:
            path: dist/daylight-visualizer


  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
