on:
  pull_request:
    paths:
      - '.github/workflows/services.yml'
      - 'src/**'
      - 'e2e/**'

jobs:
  pnpm-install:
    uses: ./.github/workflows/.pnpm_install.yaml

  lint:
    needs: pnpm-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --prefer-offline --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      - run: pnpm exec nx affected -t lint

  build:
    needs: pnpm-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: |
          echo "VITE_BUILD_SHA=e2e" | tee -a $GITHUB_WORKSPACE/.env.local
          echo "VITE_GEOAPIFY_API_KEY=${{ secrets.GEOAPIFY_API_KEY }}" | tee -a $GITHUB_WORKSPACE/.env.local
      - run: pnpm build
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.run_attempt }}
          path: ./dist
          retention-days: 1

  test-e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --prefer-offline --frozen-lockfile
      - uses: actions/download-artifact@v5
        with:
          name: build-${{ github.run_attempt }}
          path: ./dist
      - run: pnpm exec playwright install --with-deps
      - run: pnpm exec nx run e2e

  test-unit:
    needs: pnpm-install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --prefer-offline --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4
      - run: pnpm exec nx affected -t test --coverage
      - if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_attempt }}
          path: ./coverage
