on:
  pull_request:

jobs:
  pnpm_install:
    uses: ./.github/workflows/.pnpm_install.yml
    with:
      with_cache: true

  lint:
    runs-on: ubuntu-latest
    needs: pnpm_install
    steps:
      - uses: actions/checkout@v4
      - run: echo "store-dir=.pnpm-store" | tee -a $GITHUB_WORKSPACE/.npmrc
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: actions/cache@v4
        with:
          path: |
            .pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.54.2-noble
    needs: pnpm_install
    steps:
      - uses: actions/checkout@v4
      - run: echo "store-dir=.pnpm-store" | tee -a $GITHUB_WORKSPACE/.npmrc
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - uses: actions/cache@v4
        with:
          path: |
            .pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install --prefer-offline --frozen-lockfile
      - run: |
          echo "VITE_BUILD_SHA=e2e" | tee -a $GITHUB_WORKSPACE/.env.local
          echo "VITE_GEOAPIFY_API_KEY=${{ secrets.GEOAPIFY_API_KEY }}" | tee -a $GITHUB_WORKSPACE/.env.local
      - run: pnpm build
      - run: pnpm test:e2e
        env:
          HOME: /root
